---
- name: Polytech VM install
  hosts: localhost

  roles:

    # Common role that will allways be executed
    # For common updates, main configurations, ...
    - role: common
      tags:
        - always # always executed regarless of the tags
        
    # Java role for jvm developement
    - role: java
      vars:
        default_jdk: 'default-jre'
      tags:
        - java
    
    # VSCode IDE 
    - role: vscode-snap
      vars:
        insiders: true
      tags:
        - vscode
...
