---
- name: Polytech VM install
  hosts: localhost

  roles:
    # Common role that will allways be executed
    # For common updates, main configurations, ...
    - role: common
      tags:
        - allways # allways executed regarless of the tags

    # Fix an issue with ubuntu missing 'jammy-updates' repository on polytech development VM
    - role: fix-ubuntu
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'jammy'
      tags:
        - fix-ubuntu

...