
- name: Ensure jammy-update is configured to fix libc6 dependencies
  become: true
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb\s+{{item.url}}\s+jammy-updates.*{{item.repo}}'
    line: 'deb {{item.url}} jammy-updates {{item.repo}}'
  loop:
    - {"url": "http://fr.archive.ubuntu.com/ubuntu/", "repo": "main"}
    - {"url": "http://fr.archive.ubuntu.com/ubuntu/", "repo": "restricted"}
    - {"url": "http://fr.archive.ubuntu.com/ubuntu/", "repo": "universe"} 
    - {"url": "http://fr.archive.ubuntu.com/ubuntu/", "repo": "multiverse"} 

- name: Update apt cache
  become: yes
  when: ansible_pkg_mgr == 'apt'
  apt:
    force_apt_get: yes
    update_cache: yes
