---

- name: Install "code-insiders"
  when: insiders == true
  become: true
  community.general.snap:
    name: 
      - code-insiders
    channel: latest/stable
    classic: true

- name: Install "vscode" 
  when: insiders == false
  become: true
  community.general.snap:
    name: 
      - code
    channel: latest/stable
    classic: true

- name: Shortcut "code" for "code-insiders"
  when: insiders == true
  become: true
  ansible.builtin.copy:
    src: code
    dest: /usr/local/bin/code
    mode: u=rx,g=rx,o=rx

- name: Remove shortcut "code" for "code-insiders"
  when: insiders == false
  become: true
  ansible.builtin.file:
    path: /usr/local/bin/code
    state: absent
...
