---

- name: Fetch Java version
  shell: java --version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- name: Install java openjdk
  become: yes
  when: java_version.rc != 0 
  package:
    name: "{{ default_jdk }}"
    state: latest

- name: Install java Pre-requisites
  become: yes
  package:
    name: maven
    state: latest

...